# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ccb6d88479c4514cc83805ab3bee9efa3459ffab81fd3019527462cd9ec22631f7cd48dc07d72dc412f4c9c13850f3c2d176ca28f1164e1443aa914f7dd0c9b

test:
  secret_key_base: f2f71bb3d9065a4a71754f005bc30c4e6bfee4a614e2897010420f30bb69715f235f4a267fc764aacba91490743a662d2424b1dd01de7af26eea4e1fe3a8a7a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
